---
- name:  Display specific ansible_facts
  hosts: all
  tasks: 
  - name:  Display specific facts
    ansible.builtin.debug:
      msg: >
         Host '{{ ansible_facts["fqdn"] }}' with python version '{{ ansible_facts["python_version"] }}' has '{{ ansible_facts["processor_count"] }}' processors and '{{ ansible_facts["memtotal_mb"] }} MiB of total system memory.
