---
- name:  Restart HTTPD if Postfix is Running
  hosts: webserver
  tasks:
  - name:  Get HTTPD server status
    ansible.builtin.command:  /usr/bin/systemctl is-active httpd.service
    register:  result
  - name:  Print result
    ansible.builtin.debug:
      var:  result
  - name:  Restart service
    ansible.builtin.service:
      name:  httpd
      state:  restarted
    when:  result.rc == 0
