---
- name:  Examine all the stat output of /etc/passwd
  hosts:  dev
  tasks:
  - name:  stat /etc/passwd
    ansible.builtin.stat:
      path:  /etc/passwd
    register:  results
  - name:  Display stat results
    ansible.builtin.debug:
      msg:  "{{ results }}"
