---
- name:  Check privilege escalation
  hosts:  webserver
  become:  true
  tasks:
  - name:  Remove httpd
    ansible.builtin.dnf:
      name: httpd
      state:  absent

  - name:  Install httpd
    ansible.builtin.dnf:
      name: httpd
      state:  present

